gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: 127.0.0.1   #The host ip to bind to
    client:
        firewall: main
        session_handler: "@Symfony\\Component\\HttpFoundation\\Session\\Storage\\Handler\\PdoSessionHandler"
